apiVersion: pinsky-three/compiled-agent/v1alpha1
kind: Agent
metadata:
  name: agent_a
  namespace: pinsky.studio
spec:
  framework: Rig
  configModel:
    provider: openrouter
    model: openai/gpt-4o-mini  
  skills:
    - @std/methodic_agent
  tools: 
    - @std/browser_providers
    - @std/computer_us
  config:
    systemMessage: "You are a helpful AI assistant."
    temperature: 0.7